version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"

  - package-ecosystem: "pip"
    directory: "/.github/requirements"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    groups:
      requirements:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/tests/ts-tools"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    groups:
      ts-tools:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/tests/jscpd-tools"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    groups:
      jscpd-tools:
        patterns:
          - "*"
