"""Minimal YAML read/write for .standard.yml (no external dependencies)."""

import os
import re


def _yaml_scalar(value):
    """Format a Python value as a YAML scalar."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        if not value:
            return "''"
        if re.search(r"[:{}\[\],&*#?|>!%@`]", value) or value in (
            "true",
            "false",
            "yes",
            "no",
            "null",
        ):
            return f"'{value}'"
        return value
    return str(value)


def _parse_yaml_scalar(raw):
    """Parse a YAML scalar string to a Python value."""
    s = raw.strip()
    if not s or s == "null":
        return None
    if s in ("true", "yes"):
        return True
    if s in ("false", "no"):
        return False
    if len(s) >= 2 and s[0] == s[-1] and s[0] in ("'", '"'):
        return s[1:-1]
    try:
        return int(s)
    except ValueError:
        pass
    try:
        return float(s)
    except ValueError:
        pass
    return s


def write_config(path, data):
    """Write a flat or one-level-nested dict as YAML."""
    lines = ["# Generated by standard-ci — do not edit manually", ""]
    for key, value in data.items():
        if isinstance(value, dict):
            lines.append(f"{key}:")
            for k, v in value.items():
                lines.append(f"  {k}: {_yaml_scalar(v)}")
        elif isinstance(value, list):
            lines.append(f"{key}:")
            for item in value:
                lines.append(f"  - {_yaml_scalar(item)}")
        else:
            lines.append(f"{key}: {_yaml_scalar(value)}")
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))


def _parse_lines(lines):
    """Parse YAML lines into a dict. Shared by read_config and read_config_string."""
    data = {}
    current_key = None
    current_is_list = False
    for raw_line in lines:
        stripped = raw_line.rstrip("\n")
        if not stripped or stripped.lstrip().startswith("#"):
            continue
        indent = len(stripped) - len(stripped.lstrip())
        content = stripped.strip()
        if indent >= 2 and current_key is not None:
            if content.startswith("- "):
                if not current_is_list:
                    data[current_key] = []
                    current_is_list = True
                data[current_key].append(
                    _parse_yaml_scalar(content[2:])
                )
            elif ":" in content:
                k, _, v = content.partition(":")
                k = k.strip()
                v = v.strip()
                if not isinstance(data.get(current_key), dict):
                    data[current_key] = {}
                data[current_key][k] = _parse_yaml_scalar(v)
        elif ":" in content:
            k, _, v = content.partition(":")
            k = k.strip()
            v = v.strip()
            if v:
                data[k] = _parse_yaml_scalar(v)
                current_key = None
                current_is_list = False
            else:
                current_key = k
                current_is_list = False
                data[current_key] = {}
    return data


def read_config(path):
    """Read a flat or one-level-nested YAML file into a dict."""
    if not os.path.exists(path):
        return {}
    with open(path) as f:
        return _parse_lines(f)


def read_config_string(text):
    """Parse a .standard.yml string into a dict."""
    return _parse_lines(text.splitlines(keepends=True))
