#!/usr/bin/env bash
set -euo pipefail

FORCE=false
UNINSTALL=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --force)     FORCE=true; shift ;;
        --uninstall) UNINSTALL=true; shift ;;
        -h|--help)
            echo "Usage: $0 [--force] [--uninstall]"
            echo ""
            echo "Install a git pre-commit hook that runs diff-aware quality scripts locally."
            echo ""
            echo "Options:"
            echo "  --force       Install even if .pre-commit-config.yaml exists"
            echo "  --uninstall   Remove the installed pre-commit hook"
            echo "  -h, --help    Show this help message"
            echo ""
            echo "Auto-detects available checks by looking for:"
            echo "  - .clang-tidy                   → diff-clang-tidy.sh"
            echo "  - cppcheck.suppress or cppcheck → diff-cppcheck.sh"
            echo "  - .clang-format                 → diff-clang-format.sh"
            echo "  - naming-exceptions.txt          → diff-file-naming.sh"
            echo "  - scripts/diff-*.sh present     → corresponding check"
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || {
    echo "Error: not inside a git repository."
    exit 1
}

HOOK_PATH="$REPO_ROOT/.git/hooks/pre-commit"
MARKER="# Generated by standard/install-hooks.sh"

if $UNINSTALL; then
    if [ -f "$HOOK_PATH" ] && grep -q "$MARKER" "$HOOK_PATH"; then
        rm "$HOOK_PATH"
        echo "Removed pre-commit hook: $HOOK_PATH"
    else
        echo "No install-hooks.sh hook found at $HOOK_PATH"
    fi
    exit 0
fi

if [ -f "$REPO_ROOT/.pre-commit-config.yaml" ] && ! $FORCE; then
    echo "Found .pre-commit-config.yaml — this repo uses the pre-commit framework."
    echo "Run 'pre-commit install' instead, or use --force to override."
    exit 0
fi

if [ -f "$HOOK_PATH" ] && ! grep -q "$MARKER" "$HOOK_PATH"; then
    echo "Error: $HOOK_PATH already exists and was not generated by this script."
    echo "Use --force to overwrite, or back it up first."
    if ! $FORCE; then
        exit 1
    fi
fi

SCRIPTS_DIR="$REPO_ROOT/scripts"
CHECKS=()

if [ -f "$REPO_ROOT/.clang-tidy" ] && [ -f "$SCRIPTS_DIR/diff-clang-tidy.sh" ]; then
    CHECKS+=("clang-tidy")
fi

if [ -f "$SCRIPTS_DIR/diff-cppcheck.sh" ]; then
    CHECKS+=("cppcheck")
fi

if [ -f "$REPO_ROOT/.clang-format" ] && [ -f "$SCRIPTS_DIR/diff-clang-format.sh" ]; then
    CHECKS+=("clang-format")
fi

if [ -f "$SCRIPTS_DIR/diff-file-naming.sh" ]; then
    CHECKS+=("file-naming")
fi

if [ -f "$SCRIPTS_DIR/diff-iwyu.sh" ]; then
    CHECKS+=("iwyu")
fi

if [ -f "$SCRIPTS_DIR/diff-test-mirror.sh" ]; then
    CHECKS+=("test-mirror")
fi

if [ ${#CHECKS[@]} -eq 0 ]; then
    echo "No diff-* scripts found in $SCRIPTS_DIR — nothing to install."
    echo "Copy scripts from the standard repo first."
    exit 1
fi

echo "Detected checks: ${CHECKS[*]}"

{
cat << 'HOOK_HEADER'
#!/usr/bin/env bash
# Generated by standard/install-hooks.sh
# Runs diff-aware quality checks on staged files before each commit.
# To bypass: git commit --no-verify

set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel)
SCRIPTS_DIR="$REPO_ROOT/scripts"

# Diff against HEAD for staged changes (pre-commit context)
BASE="HEAD"

PASS=0
FAIL=0
SKIP=0

run_check() {
    local name="$1"
    shift
    echo "--- $name ---"
    if "$@"; then
        echo "  PASS: $name"
        PASS=$((PASS + 1))
    else
        echo "  FAIL: $name"
        FAIL=$((FAIL + 1))
    fi
}

HOOK_HEADER

for check in "${CHECKS[@]}"; do
    case "$check" in
        clang-tidy)
            cat << 'CT'
# clang-tidy — requires compile_commands.json in build/
if [ -d "$REPO_ROOT/build" ] && [ -f "$REPO_ROOT/build/compile_commands.json" ]; then
    run_check "clang-tidy" "$SCRIPTS_DIR/diff-clang-tidy.sh" "$BASE" build
else
    echo "--- clang-tidy ---"
    echo "  SKIP: no build/compile_commands.json (run cmake first)"
    SKIP=$((SKIP + 1))
fi

CT
            ;;
        cppcheck)
            if [ -f "$REPO_ROOT/cppcheck.suppress" ]; then
                echo 'CPPCHECK_SUPPRESS="$REPO_ROOT/cppcheck.suppress" run_check "cppcheck" "$SCRIPTS_DIR/diff-cppcheck.sh" "$BASE"'
            else
                echo 'run_check "cppcheck" "$SCRIPTS_DIR/diff-cppcheck.sh" "$BASE"'
            fi
            echo ""
            ;;
        clang-format)
            echo 'run_check "clang-format" "$SCRIPTS_DIR/diff-clang-format.sh" "$BASE"'
            echo ""
            ;;
        file-naming)
            if [ -f "$REPO_ROOT/naming-exceptions.txt" ]; then
                echo 'run_check "file-naming" "$SCRIPTS_DIR/diff-file-naming.sh" "$BASE" "$REPO_ROOT/naming-exceptions.txt"'
            else
                echo 'run_check "file-naming" "$SCRIPTS_DIR/diff-file-naming.sh" "$BASE"'
            fi
            echo ""
            ;;
        iwyu)
            cat << 'IWYU'
# IWYU — non-blocking by default
if [ -d "$REPO_ROOT/build" ] && [ -f "$REPO_ROOT/build/compile_commands.json" ]; then
    echo "--- iwyu ---"
    if "$SCRIPTS_DIR/diff-iwyu.sh" "$BASE" build; then
        echo "  PASS: iwyu"
    else
        echo "  INFO: iwyu (non-blocking)"
    fi
else
    echo "--- iwyu ---"
    echo "  SKIP: no build/compile_commands.json"
fi

IWYU
            ;;
        test-mirror)
            echo 'run_check "test-mirror" "$SCRIPTS_DIR/diff-test-mirror.sh" "$BASE"'
            echo ""
            ;;
    esac
done

cat << 'HOOK_FOOTER'
# --- Summary ---
echo ""
echo "=== Pre-commit Summary ==="
echo "  Passed: $PASS"
echo "  Failed: $FAIL"
echo "  Skipped: $SKIP"

if [ "$FAIL" -gt 0 ]; then
    echo ""
    echo "Commit blocked — fix the failures above or use 'git commit --no-verify' to bypass."
    exit 1
fi

exit 0
HOOK_FOOTER
} > "$HOOK_PATH"

chmod +x "$HOOK_PATH"

echo ""
echo "Installed pre-commit hook: $HOOK_PATH"
echo ""
echo "Enabled checks:"
for check in "${CHECKS[@]}"; do
    echo "  - $check"
done
echo ""
echo "To remove: $0 --uninstall"
echo "To bypass once: git commit --no-verify"
